//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapXmlHandler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestTrip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestTrip() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapXmlHandler.TestTrip", typeof(TestTrip).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TripHeaderID&quot;: 9000932,
        ///  &quot;SrcBU&quot;: 2000,
        ///  &quot;DestBU&quot;: 2011,
        ///  &quot;TripDate&quot;: &quot;2018-01-18T07:04:00&quot;,
        ///  &quot;PlannedRoute&quot;: true,
        ///  &quot;PlannedRouteID&quot;: &quot;TR4_27870&quot;,
        ///  &quot;Vehicle&quot;: {
        ///    &quot;VehID&quot;: 11016,
        ///    &quot;VehRegno&quot;: &quot;FV46JLGP&quot;,
        ///    &quot;VehMake&quot;: &quot;WHITE RX FRIDGE BAKKIE&quot;,
        ///    &quot;VehModel&quot;: &quot;2017-01-01T00:00:00&quot;,
        ///    &quot;VehType&quot;: &quot;293&quot;,
        ///    &quot;VehMaxLoad&quot;: 770,
        ///    &quot;VehDesc&quot;: &quot;IZUZU&quot;,
        ///    &quot;VehNumber&quot;: &quot;VEH.00019 &quot;,
        ///    &quot;VehLength&quot;: 223,
        ///    &quot;VehWidth&quot;: 170,
        ///    &quot;VehHeight&quot;: 155
        ///  },
        ///  &quot;Driver&quot;: {
        ///    &quot;Dr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Trip_9000932 {
            get {
                return ResourceManager.GetString("Trip_9000932", resourceCulture);
            }
        }
    }
}
